spring:
  profiles.active: local

---

spring:
  profiles: local
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        ejb:
          naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/G4
    username: grupo4
    password: ${USER_PWD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG
server:
  port: 8081

---

spring:
  profiles: deploy
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        ejb:
          naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://35.197.220.26/G4
    username: grupo4
    password: ${USER_PWD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework:
        web: DEBUG